/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.ProjetoNetbeansVogel;

/**
 *
 * @author abner
 */
public class MENU extends javax.swing.JFrame {
    private final biblioteca BIBLIOTECA = new biblioteca();
    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BOTAOcadastroLeitor = new javax.swing.JButton();
        BOTAOalugar = new javax.swing.JButton();
        BOTAOcadastroLivro = new javax.swing.JButton();
        BOTAOdevolver = new javax.swing.JButton();
        BOTAOleitores = new javax.swing.JButton();
        BOTAOlivros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("The Biblioteca");

        BOTAOcadastroLeitor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BOTAOcadastroLeitor.setText("Cadastro leitor");
        BOTAOcadastroLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOcadastroLeitorActionPerformed(evt);
            }
        });

        BOTAOalugar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BOTAOalugar.setText("Alugar");
        BOTAOalugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOalugarActionPerformed(evt);
            }
        });

        BOTAOcadastroLivro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BOTAOcadastroLivro.setText("Cadastro de livros");
        BOTAOcadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOcadastroLivroActionPerformed(evt);
            }
        });

        BOTAOdevolver.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BOTAOdevolver.setText("Devolver");
        BOTAOdevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOdevolverActionPerformed(evt);
            }
        });

        BOTAOleitores.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BOTAOleitores.setText("Leitores ativos");
        BOTAOleitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOleitoresActionPerformed(evt);
            }
        });

        BOTAOlivros.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BOTAOlivros.setText("Livros Existentes");
        BOTAOlivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOlivrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BOTAOcadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BOTAOlivros))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BOTAOcadastroLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BOTAOalugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BOTAOdevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BOTAOleitores, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTAOcadastroLeitor)
                    .addComponent(BOTAOlivros))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTAOleitores)
                    .addComponent(BOTAOcadastroLivro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTAOalugar)
                    .addComponent(BOTAOdevolver))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAOcadastroLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOcadastroLeitorActionPerformed
     TELAcadastroLeitor cadastroleitor = new TELAcadastroLeitor(this);
        cadastroleitor.setVisible(true);
    }//GEN-LAST:event_BOTAOcadastroLeitorActionPerformed

    private void BOTAOlivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOlivrosActionPerformed
         TELAlivrosExistentes livrosExistentes = new TELAlivrosExistentes(this, this.BIBLIOTECA);
        livrosExistentes.setVisible(true);
    }//GEN-LAST:event_BOTAOlivrosActionPerformed

    private void BOTAOcadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOcadastroLivroActionPerformed
           TELAcadastrarLivro cadaastroLivro = new TELAcadastrarLivro(this, this.BIBLIOTECA);
        cadaastroLivro.setVisible(true);
    }//GEN-LAST:event_BOTAOcadastroLivroActionPerformed

    private void BOTAOleitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOleitoresActionPerformed
             TELAleitoresAtivos leitoresAtivos = new TELAleitoresAtivos(this, this.BIBLIOTECA);
             leitoresAtivos.setVisible(true);
    }//GEN-LAST:event_BOTAOleitoresActionPerformed

    private void BOTAOalugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOalugarActionPerformed
           TELAalugar alugar = new TELAalugar(this, this.BIBLIOTECA);
        alugar.setVisible(true);
    }//GEN-LAST:event_BOTAOalugarActionPerformed

    private void BOTAOdevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOdevolverActionPerformed
          TELAdevolverLivro alugar = new TELAdevolverLivro(this, this.BIBLIOTECA);
        alugar.setVisible(true);
    }//GEN-LAST:event_BOTAOdevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAOalugar;
    private javax.swing.JButton BOTAOcadastroLeitor;
    private javax.swing.JButton BOTAOcadastroLivro;
    private javax.swing.JButton BOTAOdevolver;
    private javax.swing.JButton BOTAOleitores;
    private javax.swing.JButton BOTAOlivros;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
