/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.senac.ProjetoNetbeansVogel;
import javax.swing.JOptionPane;
/**
 *
 * @author abner
 */
public class TELAcadastrarLivro extends javax.swing.JDialog {
     private biblioteca BIBLIOTECA;
    /**
     * Creates new form TELAcadastrarLivro
     */
    public TELAcadastrarLivro(java.awt.Frame parent, biblioteca BIBLIOTECA) {
        super(parent);
        this.BIBLIOTECA = BIBLIOTECA;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NomeAutor = new javax.swing.JTextField();
        generoLIVRO = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        BOTAOcadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Cadastre Livros aqui");

        jLabel2.setText("Nome do Livro:");

        NomeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeLivroActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome Autor:");

        NomeAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAutorActionPerformed(evt);
            }
        });

        generoLIVRO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aventura", "Poema", "Hístoria", "Terror", "Aventura", "Misterio", "Criminal", "Manga", " " }));
        generoLIVRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoLIVROActionPerformed(evt);
            }
        });

        jLabel4.setText("Gênero Do Livro");

        BOTAOcadastrar.setText("Cadastrar");
        BOTAOcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOcadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BOTAOcadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(generoLIVRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoLIVRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTAOcadastrar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generoLIVROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoLIVROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoLIVROActionPerformed

    private void BOTAOcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOcadastrarActionPerformed
       String nameLIVROS = NomeLivro.getText();
       String nameAutor = NomeAutor.getText();
       String generoLivro = (String) generoLIVRO.getSelectedItem();
       boolean Livro_já_Existe = false;
       
       for(LIVRO livro : biblioteca.getLivros()){
           if(livro.GetName().equals(NomeLivro)){
               Livro_já_Existe = true;
           }
       }
       
       if((!Livro_já_Existe) && (!nameAutor.isEmpty()) && (!nameLIVROS.isEmpty())){
           LIVRO livro = new LIVRO(
           NomeLivro.getText(),
           NomeAutor.getText(),
           generoLivro);
           
          BIBLIOTECA.addLivro(livro);
          JOptionPane.showMessageDialog(this, "O Livro foi cadastrado com sucesso!");
            this.dispose();
       }
         else if((!nameAutor.isEmpty()) && (nameLIVROS.isEmpty())){
            JOptionPane.showMessageDialog(this, "Cade o NOME meu mano?.");
        }
        else if((nameAutor.isEmpty()) && (nameLIVROS.isEmpty())){
            JOptionPane.showMessageDialog(this, "Cade TUDO meu mano???.");
        }
        
         else if(Livro_já_Existe) {
            JOptionPane.showMessageDialog(this, "Este livro já foi cadastrado!");
        }
 
        else if((nameAutor.isEmpty()) && (!nameLIVROS.isEmpty())){
            JOptionPane.showMessageDialog(this, "Cade o AUTOR meu mano?.");
        }
        
       
    }//GEN-LAST:event_BOTAOcadastrarActionPerformed

    private void NomeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLivroActionPerformed

    private void NomeAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAutorActionPerformed

    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAOcadastrar;
    private javax.swing.JTextField NomeAutor;
    private javax.swing.JTextField NomeLivro;
    private javax.swing.JComboBox<String> generoLIVRO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
